### ISSUE TITLE
Make it possible to retrieve multiple documents by id

### ISSUE THREAD

**Issue by rutger-hertoghe** [Poolstok/MongoDB#10]

**Comment by Milko-B** [comment]
@rutger-hertoghe Kun je wat context geven?

**Comment by rutger-hertoghe** [comment]
Het is zo dat als je via FindInCollection meerdere documenten probeert op te halen op Id's, je een lege lijst terugkrijgt. Dit omdat id's moeten worden opgehaald met de specificatie dat het om een objectID gaat. Een operator voor meerdere id's is dus handig. Wanneer je documenten gaat ophalen kan je nu meerdere documenten waarvan je het id kent, gaan ophalen met de filter "_id" = OnIds(_vectorVanIds_)
